adusted terraform check based on requirements

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -38,7 +38,7 @@ jobs:
         id: priv-check
         working-directory: scripts
         run: |
-          is_priv=$(./check-privileged-user.sh ${{ github.triggering_actor }})
+          is_priv=$(./check-privileged-user.sh ${{ github.triggering_actor }} ${{ secrets.REPO_AUTHORIZED_USERS }})
           echo "is_priv=$is_priv" >> $GITHUB_OUTPUT
           if [ "$is_priv" = "true" ]; then
             echo "${{ github.triggering_actor }} is a privileged user."
@@ -80,16 +80,26 @@ jobs:
         working-directory: scripts
         run: |
           status=0
-          ./terraform-check.sh || status="$?"
+          set +e
+          ./terraform-check.sh
+          status="$?"
+          set -e
           if [ "$status" -eq 0 ]; then
-            clean_deploy='true'
-            echo "Deployment is a clean deploy."
-          elif [ "$status" -eq 1 ]; then
             clean_deploy='false'
-            echo "Deployment is not a clean deploy, so terraform apply will not be run."
+            echo "No changes were found to the AWS infrastructure. Exiting."
+          elif [ "$status" -eq 1 ]; then
+            clean_deploy='true'
+            echo "Deployment is a clean deploy with only changes to ECS detected."
+          elif [ "$status" -eq 2 ]; then
+            clean_deploy='false'
+            echo "Deployment is not a clean deploy, so changes will not be applied."
           elif [ "$status" -eq 255 ]; then
             clean_deploy='err'
             echo "There is a syntax error in the terraform configuration. Aborting workflow."
+            exit 1
+          else
+            clean_deploy='err'
+            echo "Uncaught exit code in the terraform check script. Aborting workflow."
             exit 1
           fi
           echo "clean_deploy=$clean_deploy" >> $GITHUB_OUTPUT
