add verbose output

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -76,22 +76,26 @@ jobs:
       
       - name: Run terraform plan
         id: tf-plan
-        if: ${{ github.event_name == 'push' || github.event.inputs.tf-cmd == 'plan' }}
+        if: ${{ (github.event_name == 'push') || (github.event.inputs.tf-cmd == 'plan') }}
         working-directory: scripts
         run: |
           status=0
           ./terraform-check.sh || status="$?"
           if [ "$status" -eq 0 ]; then
             clean_deploy='true'
+            echo "Deployment is a clean deploy"
           elif [ "$status" -eq 1 ]; then
             clean_deploy='false'
+            echo "Deployment is a clean deploy"
           elif [ "$status" -eq 255 ]; then
             clean_deploy='err'
+            echo "There is a syntax error in the terraform configuration"
+            exit 1
           fi
           echo "clean_deploy=$clean_deploy" >> $GITHUB_OUTPUT
       
       - name: Run terraform apply
-        if: ${{ ( github.event.inputs.tf-cmd == 'apply' || steps.tf-plan.outputs.clean_deploy == 'true' ) }}
+        if: ${{ (steps.tf-plan.outputs.clean_deploy == 'true') || (github.event.inputs.tf-cmd == 'apply') }}
         working-directory: scripts/terraform
         run: |
           clean_deploy=${{ steps.tf-plan.outputs.clean_deploy }}
